<?php

/**
 * @file
 * Provides customization for dcd site.
 */

use Symfony\Cmf\Component\Routing\RouteObjectInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dcd_utility_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Set fields to be disabled for all the forms.
  if ($form_id == 'user_register_form') {
    $request = \Drupal::request();
    if ($route = $request->attributes->get(RouteObjectInterface::ROUTE_OBJECT)) {
      $route->setDefault('_title', 'Register here for #DCD19');
    }
  }

  if ($form_id == 'contact_message_volunteering_form_drupal_camp_de_form') {
    $form['actions']['submit']['#value'] = t('Submit');
    $form['actions']['preview']['#access'] = FALSE;
  }

  if ($form_id == 'contact-message-registration-block-form') {
    $form['actions']['submit']['#value'] = t('Submit');
    $form['actions']['preview']['#access'] = FALSE;
  }

  // Cutomize sites login form.
  if ($form_id == 'user_login_form') {
    $form['register_message'] = [
      '#markup' => t('If you are not already registered for #DCD19. Register %here.', [
        '%here' => Link::fromTextAndUrl(t('here'), Url::fromRoute('user.register'))->toString(),
      ]),
      '#weight' => 100,
    ];
  }
}
