<?php
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

use Drupal\Component\Utility\Html;

/**
 * Preprocess variables for html templates.
 * @param $variables
 */
function dcd16_preprocess_html(&$variables) {
  $variables['path_info']['args'] = FALSE;
  $path = \Drupal::request()->getPathInfo();
  if ($path) {
    $variables['attributes']['class'][] = Html::cleanCssIdentifier(ltrim($path, '/'));
  }
}
